# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Huawei Inc.

stages:
  - compliance
  - build
  - test

include:
 - project: 'OSTC/infrastructure/pipelines'
   file:
    # Include shared IP compliance jobs
    - 'dco.yaml'
    - 'reuse.yaml'
 # Include the generic .workspace and .build jobs.
 - local: '/.ostc-ci/build-generic.yaml'
 # Include the set of build flavours.
 - local: '/.ostc-ci/build-flavours.yaml'
 # Include the set of templates and jobs that use default.xml
 - local: '/.ostc-ci/default-targets.yaml'
 # Include the set of templates and jobs that use develop.xml
 - local: '/.ostc-ci/develop-targets.yaml'

dco:
  extends: .dco

reuse:
  extends: .reuse

# Customize the generic .build job, included from build-generic.yaml above,
# with an unique set of rules that enable the job and an override for the
# OHOS_MANIFEST_BRANCH variable.
.build:
  variables:
    # When building, use the manifest repository from the branch being proposed.
    # This setting is only valid in the manifest repository.
    OHOS_MANIFEST_BRANCH: "$CI_COMMIT_REF_NAME"
  rules:
    # Run the build when a merge request is created and the corresponding
    # manifest is modified. Or when the pipeline definition, or its components,
    # are changed.
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - $OHOS_MANIFEST_NAME
        - .gitlab-ci.yml
        - .ostc-ci/*.yaml
  artifacts:
    # Disable collection of image artifacts. They are not used here and they
    # are expensive to upload and store.
    paths: []
