# SPDX-License-Identifier: Apache-2.0
#
# Copyright 2020-2021 Huawei Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

stages:
  - compliance
  - build
  - test

include:
 - project: 'OSTC/infrastructure/pipelines'
   file:
    # Include shared IP compliance jobs
    - 'dco.yaml'
    - 'reuse.yaml'
    # Include the shared workspace job used as the foundation of our .build job.
    - 'workspace.yaml'
 # Include the generic .build job.
 - local: '/.ostc-ci/build-generic.yaml'
 # Include the set of build flavours.
 - local: '/.ostc-ci/build-flavours.yaml'
 # Include the set of templates and jobs that use default.xml
 - local: '/.ostc-ci/default-targets.yaml'
 # Include the set of templates and jobs that use develop.xml
 - local: '/.ostc-ci/develop-targets.yaml'

dco:
  extends: .dco

reuse:
  extends: .reuse

# Customize the generic .build job, included from build-generic.yaml above,
# with an unique set of rules that enable the job and an override for the
# OHOS_MANIFEST_BRANCH variable.
.build:
  variables:
    # When building, use the manifest repository from the branch being proposed.
    # This setting is only valid in the manifest repository.
    OHOS_MANIFEST_BRANCH: "$CI_COMMIT_REF_NAME"
  rules:
    # Run the build when a merge request is created and the corresponding
    # manifest is modified. Or when the pipeline definition, or its components,
    # are changed.
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - $OHOS_MANIFEST_NAME
        - .gitlab-ci.yml
        - .ostc-ci/*.yaml
