# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Huawei Inc.

stages:
  - compliance
  - build
  - test
  - deploy

include:
 - project: 'OSTC/infrastructure/pipelines'
   file:
    # Include shared IP compliance jobs
    - 'dco.yaml'
    - 'reuse.yaml'
 # TODO: merge this into one file, for simplicity.
 # Include the generic .workspace and .build jobs.
 - local: '/.ostc-ci/build-generic.yaml'
 # Include the set of build flavours.
 - local: '/.ostc-ci/build-flavours.yaml'
 # Include the set of jobs using the default manifest.
 - local: '/.ostc-ci/default-targets.yaml'

dco:
  extends: .dco

reuse:
  extends: .reuse

# Customize the generic .build job, included from build-generic.yaml above,
# with an unique set of rules that enable the job and an override for the
# OHOS_MANIFEST_BRANCH variable.
.build:
  variables:
    # When building, use the manifest repository from the branch being proposed.
    # This setting is only valid in the manifest repository.
    OHOS_MANIFEST_BRANCH: "$CI_COMMIT_REF_NAME"
  rules:
    # Run the build when it is scheduled.
    - if: $CI_PIPELINE_SOURCE == "schedule"
    # Do not run pipelines for draft merge requests unless manually triggered.
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TITLE =~ /^(wip|draft):.*/i'
      when: manual
    # Run the build when a merge request is created and the corresponding
    # manifest is modified. Or when the pipeline definition, or its components,
    # are changed.
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - $OHOS_MANIFEST_NAME
        - .gitlab-ci.yml
        - .ostc-ci/*.yaml
    # Run the build when a tag is placed.
    - if: '$CI_COMMIT_TAG'
  artifacts:
    # Disable collection of image artifacts. They are not used here and they
    # are expensive to upload and store.
    paths: []

# Perform scheduled builds with glibc instead of musl.
linux-glibc-qemu-x86_64:
  extends: linux-qemu-x86_64
  variables:
    # This appends TCLIBC = "glibc" to conf/local.conf and interacts with
    # meta-ohos-core layer.
    # https://git.ostc-eu.org/OSTC/OHOS/meta-ohos/-/blob/develop/meta-ohos-core/conf/distro/openharmony-linux.conf#L11
    OHOS_BB_LOCAL_CONF_TCLIBC: glibc
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"

# Build documentation present in the repository.
build-docs:
  extends: .build-docs

# Trigger aggregation of All Scenario OS documentation.
aggregate-docs:
  extends: .aggregate-docs
  needs: [build-docs]
